require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Style/Documentation:
    Enabled: false

Metrics/BlockLength:
    Exclude:
      - 'config/environments/development.rb'

Metrics/MethodLength:
    Exclude:
      - 'db/migrate/*'

Metrics/AbcSize:
    Exclude:
      - 'db/migrate/*'
